#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo "Your e-mail $email satisfies Git policy"
    exit 0
else
    echo "Your e-mail $email doesn't satisfies Git policy"
    exit 1
fi